# Generated by Django 4.2.7 on 2023-11-26 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='название игры')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='слаг игры')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='цена игры')),
            ],
            options={
                'verbose_name': 'игра',
                'verbose_name_plural': 'игры',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='название платформы')),
                ('slug', models.SlugField(unique=True, verbose_name='слаг платформы')),
                ('information', models.CharField(max_length=100, verbose_name='информация о платформе')),
            ],
            options={
                'verbose_name': 'платформа',
                'verbose_name_plural': 'платформы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Souvenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='название сувенира')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='слаг сувенира')),
                ('information', models.CharField(max_length=128, verbose_name='информация о сувенире')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='цена сувенира')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souvenirs', to='api.game', verbose_name='игра сувенира')),
            ],
            options={
                'verbose_name': 'сувенир',
                'verbose_name_plural': 'сувениры',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ManyToManyField(related_name='games', to='api.platform', verbose_name='платформы игры'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='название девайса')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='слаг девайса')),
                ('information', models.CharField(max_length=128, verbose_name='информация о девайсе')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='цена девайса')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.platform', verbose_name='платформа девайса')),
            ],
            options={
                'verbose_name': 'девайс',
                'verbose_name_plural': 'девайсы',
                'ordering': ('title',),
            },
        ),
    ]
